os:
  - osx

install:
  - npm install
  - npm run vscode:prepublish

cache:
  directories:
    - "node_modules"

script:
  echo ">>> Run compiling and linting"
  - npm pretest
  echo ">>> Run overall extension tests"
  - npm test

notifications:
  email: false