# sudo: false

os:
  - osx
  - linux

before_install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi

install:
  - npm install
  - npm run vscode:prepublish

script:
  - npm test